# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  # moviebuyer:
  #   image: moviebuyer
  moviestore:
    image: moviestore
    build:
      context: .
      # dockerfile: MovieBuyerMin/Dockerfile
      dockerfile: src/MovieStore.Api/Dockerfile
    ports:
      - 5004:5004
      # - 5252:5252
